# Generated by Django 5.2.3 on 2025-07-02 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_date_added_alter_movie_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default='Untitled Video', max_length=255),
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(upload_to='thumb/')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='movies.movie')),
            ],
        ),
    ]
